app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/teach_spring?currentSchema=jdbc
      username: javohir
      password: admin123
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


