spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

